export const Projects = [
  {
    name: 'Portfólio -- Front-End',
    description: 'Este projeto é o meu portfólio. Ele tem como objetivo apresentar informações sobre mim e alguns dos projetos que já realizei.',
    technologies:  ['Angular', 'Typescript.js', 'SCSS', 'HTML'],
    projectUrl: "",
    repositoryUrl: 'https://github.com/WendelSantosNunes/portfolio-2024',
    imageUrl: '/assets/shahadat-rahman-O2MdroNurVw-unsplash.jpg',
  },
  {
    name: 'Netflix (Home Page) -- Front-End',
    description: 'Este projeto foi realizado para treinar o consumo de API externa no Angular 14.',
    technologies: ['Angular', 'Typescript.js', 'CSS', 'HTML'],
    projectUrl: "",
    repositoryUrl: 'https://github.com/WendelSantosNunes/Netflix-Angular',
    imageUrl: 'https://raw.githubusercontent.com/WendelSantosNunes/Netflix-Angular/main/imagem-readme/project.png',
  },
  {
    name: 'Blog-Api -- Back-End',
    description: 'Este é um projeto de back-end para uma API de blog. O objetivo é criar um CRUD com Spring Security, JWT, Spring Boot Start Mail e FlyWay, agregando assim mais complexidade do que um projeto simples.',
    technologies: ['Java', 'Spring Boot', 'Spring Boot Starte Data JPA', 'Spring Boot Starter Mail', 'Spring Security', 'JWT', 'Lombok', 'Flywaydb', 'MySql', 'Swagger'],
    projectUrl: "",
    repositoryUrl: 'https://github.com/WendelSantosNunes/Blog',
    imageUrl: '/assets/shahadat-rahman-O2MdroNurVw-unsplash.jpg',
  },
  {
    name: 'Autenticação de Usuário -- Back-End',
    description: 'Este projeto é um back-end desenvolvido com o objetivo de implementar um sistema de autenticação utilizando JWT e Spring Security. Com isso, um usuário tem a capacidade de criar uma conta na API, fazer login, editar seus dados e, se for um administrador, excluir a conta. Para atingir esse objetivo, foi utilizado o framework Spring Boot e a tecnologia JPA/Hibernate.',
    technologies: ['Java', 'Spring Boot', 'Spring Security', 'Swagger', 'JWT', 'MySql'],
    projectUrl: "",
    repositoryUrl: 'https://github.com/WendelSantosNunes/auth_usuario',
    imageUrl: '/assets/shahadat-rahman-O2MdroNurVw-unsplash.jpg',
  },
  {
    name: 'VTEX -- Front-End',
    description: 'Este projeto é o desafio para vaga de desenvolvedor Front-End Júnior na empresa VTEX.',
    technologies: ['Angular', 'Typescript.js', 'CSS', 'HTML'],
    projectUrl: "https://desafio-front-end-jr-vtex.vercel.app",
    repositoryUrl: 'https://github.com/WendelSantosNunes/Desafio-Front-End-Jr-VTEX-',
    imageUrl: 'https://raw.githubusercontent.com/WendelSantosNunes/Desafio-Front-End-Jr-VTEX-/main/imagem-readme/Project.png',
  },
];
